yarnPath: .yarn/releases/yarn-3.2.3.cjs
nodeLinker: node-modules
packageExtensions:
  "@loopback/graphql@*":
    peerDependencies:
      class-validator: "^0.13.2"
    dependencies:
      apollo-server-core: "^3.10.2"
  "@loopback/openapi-v3@*":
    peerDependencies:
      "@loopback/repository": "^5.0.3"
  "@loopback/rest@*":
    peerDependencies:
      "@loopback/repository": "^5.0.3"
